package Hashset_demo;

public class Properties {

	public static void main(String[] args) {
		System.out.println("1.Not an index based DS");
		System.out.println("they store the element according to their hash value");
		System.out.println("Hashvalue-unique integer value generated by systum");
		
		System.out.println("2.value generated for key are unique");
		System.out.println("3.Does not store duplicated elements");
		System.out.println("4.Does not store multiple null values");
		System.out.println("5.Can Store Different Data type-hetorogenous elements");
		System.out.println("6.Hash set does not follow the insertion order");
		System.out.println("7.Does not follow sorted order");
		System.out.println("8.Non-sysnchronized data structure");
	}

}
